services:
  curriculo-online:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - dependencias:/app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 8080

volumes:
  dependencias:
